<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>output-default-setting</name>
  <uuid>261f3bbf-c878-4b59-af07-e313be8ad8aa</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to a new Dados Produtos where
		the CD_Produto_GAM is 0, 
		the Desc_Produto_GAM is "nao encontrou", 
		the Estoque is 0, 
		the Marca_Produto is "nao encontrou", 
		the Valor_Caixa is 1, 
		the Valor_Margem is 1, 
		the Valor_Unitario is 1 ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
