<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Print results</name>
  <uuid>c3d0d244-6c6d-4ba4-bd28-daeb09dcde9a</uuid>
  <documentation><![CDATA[Print all the results.]]></documentation>
  <locale>en_US</locale>
  <definition><![CDATA[for each string in decision : 
- print this string ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
