<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Verify</name>
  <uuid>37e55518-8a84-463f-a701-d068306db0fb</uuid>
  <documentation><![CDATA[Verify customer's information.]]></documentation>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to the level2 verify datas computed from 
    Customer information being Customer  ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
