<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Ajuste Marca Solicitada Cliente</name>
  <uuid>c45d5ed7-7371-45ec-beb6-c5f33a96a7e9</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[for each string called 'variable1' , in the Marca_Solicitada_Clientes of the Produtos of Cotacao 
if decision is empty then set decision to variable1 ;
else set decision to decision + " / " + variable1 ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
