<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>income</name>
  <uuid>9e57b15d-2f6f-4314-bfe3-cc0eb80e38e7</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if
    'Yearly income' is less than 50000
then
    add "Income is too low" to decision;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
