<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>score</name>
  <uuid>4399890d-31a1-480e-91c1-8056af3607c2</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if
    'Credit score' is less than 300
then
    add "Score too low." to decision;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
