<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>count completed milestones</name>
  <uuid>6acd6a1c-8297-4f91-bdae-0e907071d5bf</uuid>
  <documentation><![CDATA[Count the number of completed milestones.]]></documentation>
  <locale>en_US</locale>
  <definition><![CDATA[definitions
set 'completed milestones' to the milestones of the contracts where each Milestone is completed ; 

then
set decision to the number of 'completed milestones'; 
]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
