<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>output-default-setting</name>
  <uuid>7ef35f6f-ae6c-4ef3-a611-360102762114</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to "teste" ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
