<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>check contract date</name>
  <uuid>0684698a-69cf-4a65-8fdc-16ee8f05a27a</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[definitions
    set contract to a Contract in the contracts ;
    set date to the start date of contract ;

if  date is null or date is before 1/1/2010 
 then 
    add "Error: The start date of " + the name of contract + " is incorrect." to decision;

]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
