<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>copy input to output</name>
  <uuid>c366152a-b6b9-4d23-b2ca-663171e7e931</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[--copy input
set decision to 'Check customer information' ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
