<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>stay</name>
  <uuid>1ba90f2a-5a69-4909-bfa7-af38150e21ef</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if
    the prediction of 'ML model invocation' is "F"
then
    set decision to the maximum probability of 'ML model invocation'  ;
]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
