<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Advice rule</name>
  <uuid>a3939c10-17e2-422b-a768-2c91d1bdb7be</uuid>
  <documentation><![CDATA[Builds a daily advice from the provided input.]]></documentation>
  <locale>en_US</locale>
  <definition><![CDATA[if
    Name is defined
then
    set decision to "Hello " + Name  + "! " + 'Weather advice';]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
