<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Sum inputs</name>
  <uuid>fcca8053-8648-49e1-a030-f33f78ec2825</uuid>
  <documentation><![CDATA[Use for each syntax to iterate in a list]]></documentation>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to 0;
for each number in Numbers  : 
    - set decision to decision + this number ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
