<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>output-default-setting</name>
  <uuid>95395f00-ebf4-44bb-a20a-d89be7d69300</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to true;
print "Pre-approved!";]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
