<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>output-default-setting</name>
  <uuid>28d052a2-e385-4bb6-922a-29804233254b</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[add "OK" to decision ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
