<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Average age</name>
  <uuid>ddbab7c0-95db-47fb-bc80-a72a1bfbab1c</uuid>
  <documentation><![CDATA[Check if a group contains at least a minor.]]></documentation>
  <locale>en_US</locale>
  <definition><![CDATA[definitions
set average to the average age of 'Group of people' ;

then
add "The average age in the group is "+ round(average,1) + " years old" to decision ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
