<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Is there a minor</name>
  <uuid>b5641aa5-299c-4032-b00c-5e3e3a56761c</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[definitions
set 'minor age' to 21;

if there is at least one Person in 'Group of people' 
    where the age is less than 'minor age' , 
then 
    print "Minor age is defined to " + 'minor age';
    add "There is at least one minor in the group." to decision ;
]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
