<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Scan list 1</name>
  <uuid>918caf6e-70a6-4403-af17-80144a805221</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[for each number in 'List 1' : 
    - set decision to this number ; ]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
