<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Scan list 2</name>
  <uuid>e8990dbd-7614-4c7d-8b31-ec4545bb81bc</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[for each number in 'List 1' : 
    - set decision to this number ; ]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
