<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>count the number of pending milestones</name>
  <uuid>30991076-47c2-47c9-bebc-7b5860fa7ac4</uuid>
  <documentation><![CDATA[Count the number of pending milestones.]]></documentation>
  <locale>en_US</locale>
  <definition><![CDATA[definitions
set 'non completed milestones' to the milestones of the contracts where it is not true that each Milestone is completed ; 

then
set decision to the number of 'non completed milestones'; 
]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
