<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>output-default-setting</name>
  <uuid>1eaeb128-aede-4aed-9ce5-144c1fa30da3</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to a new insurance where
        required is true, 
        the rate is 0.02;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
