<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Analyze completed milestones</name>
  <uuid>14bd9b08-3d9c-4d58-b93e-c1e28d07515c</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[definitions 
    set contract to a Contract in the contracts of 'Customer information' ;
    set milestone to a Milestone in the milestones of contract 
    where this Milestone is completed ;

then 
add the name of contract  + ", " + the name of milestone + " is completed" to decision ;
]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
