<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Completion rate</name>
  <uuid>dc9509b4-1fbd-40bd-95dd-d9d16ef098fd</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[definitions
set rate to ('Completed milestones' * 100 / ('Completed milestones' + 'Non completed milestones' ));

then 
add "Milestone completion rate is " + rate + "%" to decision ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
