<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Advice rule</name>
  <uuid>8bd4d243-465d-46dc-aca2-288c10424f74</uuid>
  <documentation><![CDATA[Builds a daily advice from the provided input.
]]></documentation>
  <locale>en_US</locale>
  <definition><![CDATA[if
    Name is defined
then
    set decision to "Hello " + Name + "!" ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
