<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>default-value-setting</name>
  <uuid>d6788cd8-d073-406f-96c8-5c4234ba34bb</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set Input to "teste" ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
