<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Select best offer</name>
  <uuid>fb4b168c-b672-437a-a2c6-a4b6e3a0ea34</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[definitions
-- Loop on potential offers
set offer to an offer in 'Ranked retention offers' ;
set cost to the estimated cost of offer;

-- Select the best offer that is below the allocated budget
-- Technical note: this rule will be evaluated once for every item in the list of offers, and in the end the most costly offer (while still below budget), will be retained.
if cost is less than 'Retention monthly budget' and
   cost is at least the estimated cost of decision 
then
    set decision to offer;
]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
