<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Equals to threshold</name>
  <uuid>cdac7915-fc80-4978-8651-9b86839597aa</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if Total equals Threshold 
then
    set decision to "Total (" + Total + ") is equal to the threshold (" + Threshold + ")";]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
