<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Print sum</name>
  <uuid>7caf48e7-f957-460b-a187-da82d87c77c8</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if
    Total is defined
then
    print "The sum of the numbers in the output list is " + Total + ".";]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
