<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Test against threshold</name>
  <uuid>77e83568-af5c-4dcd-ba0b-6773898b72e3</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if Total is more than Threshold 
then
    set decision to "Total (" + Total + ") is above the threshold (" + Threshold + ")";
else 
    set decision to "Total (" + Total + ") is below the threshold (" + Threshold + ")";
]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
