<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Scan list 2</name>
  <uuid>232fb070-d6cf-4a22-87ea-0511984419a3</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[for each number in 'List 2' : 
    - set decision to this number ; 
]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
