<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Probabilidade Preco</name>
  <uuid>2ce70943-248a-4de2-8c75-56823071b044</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to the model preditivo quotacao preco computed from
      Dados Entrada being 'Ajuste Dados Predicao'  ;

]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
