<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>add milestones</name>
  <uuid>718608f3-4512-479a-bba4-ebc8893efa16</uuid>
  <documentation><![CDATA[Complete the created data]]></documentation>
  <locale>en_US</locale>
  <definition><![CDATA[definitions
set contract to a Contract in the contracts of decision ;

then
print "Complete the " + the name of contract + " with the initial steps.";
add a new Milestone where 
                    completed is true,
                    the name is "Preparation step" to the milestones of contract  ; 
add a new Milestone where 
                    completed is false , 
                    the name is "First step" to the milestones of contract  ; 
add a new Milestone where 
                    completed is false , 
                    the name is "Step 3" to the milestones of contract  ; 
 ]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
