<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>output-default-setting</name>
  <uuid>43843523-23d1-4d22-bf06-32f92e71f443</uuid>
  <documentation><![CDATA[That's the default decision when none of the above rules are applicable.]]></documentation>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to 'Customer name' + " is rated C." ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
