<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>output-default-setting</name>
  <uuid>2954d303-eee7-499f-81e4-aa357066d616</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to "marca default" ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
