<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Valor inicial</name>
  <uuid>278e8468-47ee-41cf-afc5-d79df12d05f4</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to "" ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
