<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>check company name</name>
  <uuid>2f3f60cb-8337-4b10-81ba-8c1919617c04</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if
    the company is empty 
then
     add "Error: Company name is missing." to decision;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
