<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>check last name</name>
  <uuid>1ef24cde-3f76-411c-8694-ae528790ba56</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if
    the last name is empty
then
        add "Error: Customer name is missing." to decision ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
