<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Advice rule</name>
  <uuid>2bf14fd1-ca32-4131-90c1-59f3cc055bb1</uuid>
  <documentation><![CDATA[Builds a daily advice from the provided input.]]></documentation>
  <locale>en_US</locale>
  <definition><![CDATA[if
    Name is defined
then
    set decision to "Hello " + Name  + "! " + 'Weather advice';]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
