<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>output-default-setting</name>
  <uuid>f605df18-9fd4-4469-bfe4-2e8dffbbbbb3</uuid>
  <documentation><![CDATA[Builds a message when no advice can be given due to missing output.]]></documentation>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to "Sorry, we don't have enough information to build an advice." ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
