<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>storm rule</name>
  <uuid>821d3874-ce07-4556-b802-b81412e87302</uuid>
  <documentation><![CDATA[First priority rule.]]></documentation>
  <locale>en_US</locale>
  <definition><![CDATA[if
     Weather is storm alert 
then
    set decision to "It would be wise to stay home. There is a storm alert." ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
